# Generated by Django 3.0.8 on 2020-08-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(upload_to='pics/projects'),
        ),
    ]
