# Generated by Django 3.0.8 on 2020-08-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
